"""Bundled default-phase catalog (ported from generate_default_phases.py).

The reference clay-layer COMPONENTS ship as `.cmp` files under
`mudlab/data/default components/` (verbatim from the old app - the same ZIP-of-
Component-JSON format MudLab2's `load_cmp` reads). A default component's atoms
reference atom types by NAME; they resolve against the built-in scattering-
factor library ([atom_type_library]), so a phase built from a default component
computes a real pattern with no project atom types needed.

`build_catalog_entry` assembles named default PHASES from those components,
following the old generator's recipe: a component "code" (4-char aliases, one
per component) selects the `.cmp` files, and per-phase `based_on` / per-
component `linked_with` names wire the air-dried -> glycolated -> heated (Ca-AD /
Ca-EG / Ca-350) inheritance chains. `default_catalog_entries` lists the entries
the Add Phase dialog offers.

Covered: the single-layer clays; the expandable Ca-smectite / -vermiculite
families at 1-3 interstratified hydration states; the two-clay interstratifications
(Illite- / Kaolinite- / Talc- / Chlorite-Smectite) and three-clay ones (Illite- /
Kaolinite-Chlorite-Smectite), each with a 1-3 state smectite, at every modeled
Reichweite R0-R3. A treated phase inherits the AD's stacking ratio
(inherit_probabilities). Everything is expressed as a hydration LADDER + fixed-
clay columns and generated by `_build_family`, gated by `is_modeled` (= the
engine's `is_supported_rg` / RGbounds) - so an entry is offered exactly when a
stacking model exists for its (R, G), matching the old app's full catalog.
"""

from __future__ import annotations

import os

from mudlab.file_parsers.atom_type_library import atom_type_library_map
from mudlab.file_parsers.cmp_components import load_cmp
from mudlab.models.phase import Phase
from mudlab.models.probabilities import is_supported_rg

_COMPONENTS_DIR = os.path.join(
    os.path.dirname(__file__), os.pardir, "data", "default components"
)


def default_components_dir() -> str:
    """Absolute path to the bundled default-component `.cmp` directory."""
    return os.path.abspath(_COMPONENTS_DIR)


def load_default_component(relpath: str, atom_type_map: dict | None = None) -> list:
    """Load the component(s) in a bundled `.cmp` (path relative to
    `default_components_dir`), resolving their atoms against the built-in
    scattering-factor library by default so the result is directly computable.
    Pass an `atom_type_map` (e.g. a project's) to resolve against that instead."""
    if atom_type_map is None:
        atom_type_map = atom_type_library_map()
    path = os.path.join(default_components_dir(), relpath)
    components, _names = load_cmp(path, atom_type_map)
    return components


# ----------------------------------------------------------------------
# The recipe (ported from generate_default_phases.run)
# ----------------------------------------------------------------------
_CODE_LEN = 4  # each component is named by a 4-character alias in the "code"


def is_modeled(reichweite: int, g: int) -> bool:
    """Whether MudLab2 can build this stacking - delegates to the engine's
    RGbounds (R0 G1-6, R1 G2-4, R2 G2-3, R3 G2)."""
    return is_supported_rg(reichweite, g)

# alias -> .cmp path (relative to the default-component dir). Each smectite /
# vermiculite family carries its three interlayer hydration states: 2 water
# (2w) / 1 water (1w) / dehydrated (0w) air-dried, and 2 glycol (2g) / 1 glycol
# (1g) / heated (ht) treated.
_ALIASES = {
    "K   ": "Kaolinite.cmp",
    "I   ": "Illite.cmp",
    "Se  ": "Serpentine.cmp",
    "T   ": "Talc.cmp",
    "C   ": "Chlorite.cmp",
    "Ma  ": "Margarite.cmp",
    "L   ": "Leucophyllite.cmp",
    "Pa  ": "Paragonite.cmp",
    "Mu  ": "Muscovite.cmp",
    "dS2w": "Di-Smectite/Di-Smectite - Ca 2WAT.cmp",
    "dS1w": "Di-Smectite/Di-Smectite - Ca 1WAT.cmp",
    "dS0w": "Di-Smectite/Di-Smectite - Ca Dehydr.cmp",
    "dS2g": "Di-Smectite/Di-Smectite - Ca 2GLY.cmp",
    "dS1g": "Di-Smectite/Di-Smectite - Ca 1GLY.cmp",
    "dSht": "Di-Smectite/Di-Smectite - Ca Heated.cmp",
    "tS2w": "Tri-Smectite/Tri-Smectite - Ca 2WAT.cmp",
    "tS1w": "Tri-Smectite/Tri-Smectite - Ca 1WAT.cmp",
    "tS0w": "Tri-Smectite/Tri-Smectite - Ca Dehydr.cmp",
    "tS2g": "Tri-Smectite/Tri-Smectite - Ca 2GLY.cmp",
    "tS1g": "Tri-Smectite/Tri-Smectite - Ca 1GLY.cmp",
    "tSht": "Tri-Smectite/Tri-Smectite - Ca Heated.cmp",
    "dV2w": "Di-Vermiculite/Di-Vermiculite - Ca 2WAT.cmp",
    "dV1w": "Di-Vermiculite/Di-Vermiculite - Ca 1WAT.cmp",
    "dV0w": "Di-Vermiculite/Di-Vermiculite - Ca Dehydr.cmp",
    "dV2g": "Di-Vermiculite/Di-Vermiculite - Ca 2GLY.cmp",
    "dV1g": "Di-Vermiculite/Di-Vermiculite - Ca 1GLY.cmp",
    "dVht": "Di-Vermiculite/Di-Vermiculite - Ca Heated.cmp",
}

# A treated (EG / 350) SMECTITE component reuses the air-dried layer structure -
# it links to the AD component and inherits its cell a/b, delta_c and layer atoms,
# keeping only its own interlayer (old inherit_S).
_INHERIT_S = dict(
    inherit_ucp_a=True, inherit_ucp_b=True,
    inherit_delta_c=True, inherit_layer_atoms=True,
)
# A treated FIXED component (illite / kaolinite / ...) is identical between
# treatments, so it inherits everything from the AD copy (old inherit_all).
_INHERIT_ALL = dict(
    inherit_d001=True, inherit_default_c=True,
    inherit_interlayer_atoms=True, inherit_atom_relations=True, **_INHERIT_S,
)
# A treated phase inherits its parent's visuals + orientation + CSDS (old
# inherit_phase). inherit_probabilities is added per-phase when G > 1.
_INHERIT_PHASE = dict(
    inherit_display_color=True, inherit_sigma_star=True,
    inherit_CSDS_distribution=True,
)

# Each smectite / vermiculite family as a hydration LADDER: one column per
# interstratified state, most hydrated first, as (air-dried, glycolated, heated)
# component aliases. A treated component links to its column's air-dried alias.
_DI_SMECTITE = [("dS2w", "dS2g", "dSht"), ("dS1w", "dS1g", "dS1g"),
                ("dS0w", "dS0w", "dS0w")]
_TRI_SMECTITE = [("tS2w", "tS2g", "tSht"), ("tS1w", "tS1g", "tS1g"),
                 ("tS0w", "tS0w", "tS0w")]
_DI_VERMICULITE = [("dV2w", "dV2g", "dVht"), ("dV1w", "dV1g", "dV1g"),
                   ("dV0w", "dV0w", "dV0w")]
# smectite-state-count suffix (>1 states get a tag)
_ORDER = {1: "", 2: " (2S)", 3: " (3S)"}


def _fixed_column(alias: str) -> tuple:
    """A non-expandable clay column: the same component in AD/EG/350, inheriting
    the AD copy entirely."""
    return (alias, alias, alias, _INHERIT_ALL)


def _smectite_columns(ladder: list, n_states: int) -> list:
    """The first `n_states` hydration columns of a ladder (smectite inheritance)."""
    return [(ad, eg, ht, _INHERIT_S) for ad, eg, ht in ladder[:n_states]]


def _build_family(display: str, columns: list, max_r: int = 4) -> list:
    """Emit catalog entries for a mixed-layer family from its `columns` (each
    ``(ad_alias, eg_alias, ht_alias, inherit_dict)``; the AD alias is the
    linked_with target for the treated EG/350 components). One entry per modeled
    Reichweite (R0-R3, gated by is_modeled to the G the engine supports). The
    treated phases are based on the AD and, when there is a stacking ratio
    (G > 1), inherit it."""
    g = len(columns)
    entries = []
    for reichweite in range(max_r):
        if not is_modeled(reichweite, g):
            continue
        stem = "%s R%d Ca" % (display, reichweite)
        codes = ["".join(col[i] for col in columns) for i in range(3)]
        eg_inh = {col[1]: dict(linked_with=col[0], **col[3]) for col in columns}
        ht_inh = {col[2]: dict(linked_with=col[0], **col[3]) for col in columns}
        treated = dict(_INHERIT_PHASE)
        if g > 1:
            treated["inherit_probabilities"] = True
        entries.append((stem, [
            (dict(R=reichweite, name="%s-AD" % stem), codes[0], {}),
            (dict(R=reichweite, name="%s-EG" % stem, based_on="%s-AD" % stem,
                  **treated), codes[1], eg_inh),
            (dict(R=reichweite, name="%s-350" % stem, based_on="%s-AD" % stem,
                  **treated), codes[2], ht_inh),
        ]))
    return entries


def _smectite_family(display: str, ladder: list, max_states: int = 3) -> list:
    """A pure smectite / vermiculite at 1..max_states interstratified states."""
    out = []
    for n in range(1, max_states + 1):
        out += _build_family(display + _ORDER[n], _smectite_columns(ladder, n))
    return out


def _mixed_family(display: str, fixed: list, ladder: list,
                  max_states: int = 3) -> list:
    """A fixed clay (or clays) interstratified with a smectite at 1..max_states
    states (Illite-Smectite, Illite-Chlorite-Smectite, ...)."""
    out = []
    fixed_columns = [_fixed_column(alias) for alias in fixed]
    for n in range(1, max_states + 1):
        out += _build_family(display + _ORDER[n],
                             fixed_columns + _smectite_columns(ladder, n))
    return out


# (display name, [ (phase_kwargs, component-code, {part: component-overrides}) ])
_CATALOG: list = [
    # Single, non-expandable clays.
    ("Kaolinite", [(dict(R=0, name="Kaolinite"), "K   ", {})]),
    ("Illite", [(dict(R=0, name="Illite"), "I   ", {})]),
    ("Serpentine", [(dict(R=0, name="Serpentine"), "Se  ", {})]),
    ("Talc", [(dict(R=0, name="Talc"), "T   ", {})]),
    ("Chlorite", [(dict(R=0, name="Chlorite"), "C   ", {})]),
    ("Margarite", [(dict(R=0, name="Margarite"), "Ma  ", {})]),
    ("Leucophyllite", [(dict(R=0, name="Leucophyllite"), "L   ", {})]),
    ("Paragonite", [(dict(R=0, name="Paragonite"), "Pa  ", {})]),
    # Muscovite.cmp was bundled but never offered - faithful to the old
    # app, which shipped the component and left it out of its own list.
    # It is a perfectly good single non-expandable clay and costs a line.
    ("Muscovite", [(dict(R=0, name="Muscovite"), "Mu  ", {})]),
    # Expandable smectites / vermiculites, 1-3 interstratified hydration states.
    *_smectite_family("Di-Smectite", _DI_SMECTITE),
    *_smectite_family("Tri-Smectite", _TRI_SMECTITE),
    *_smectite_family("Di-Vermiculite", _DI_VERMICULITE),
    # Two-clay interstratifications (a fixed clay + a smectite). Illite /
    # Kaolinite / Talc pair with the di-smectite; Chlorite with the tri-smectite.
    *_mixed_family("Illite-Smectite", ["I   "], _DI_SMECTITE),
    *_mixed_family("Kaolinite-Smectite", ["K   "], _DI_SMECTITE),
    *_mixed_family("Talc-Smectite", ["T   "], _DI_SMECTITE),
    *_mixed_family("Chlorite-Smectite", ["C   "], _TRI_SMECTITE),
    # Three-clay interstratifications.
    *_mixed_family("Illite-Chlorite-Smectite", ["I   ", "C   "], _DI_SMECTITE),
    *_mixed_family("Kaolinite-Chlorite-Smectite", ["K   ", "C   "], _DI_SMECTITE),
]


def _entry_is_modeled(descr: list) -> bool:
    return all(
        is_modeled(int(kw.get("R", 0)), max(len(code) // _CODE_LEN, 1))
        for kw, code, _props in descr
    )


def default_catalog_entries() -> list:
    """`[(display_name, descr)]` for every catalog entry MudLab2 can build."""
    return [(name, descr) for name, descr in _CATALOG if _entry_is_modeled(descr)]


def build_catalog_entry(descr: list, atom_type_map: dict | None = None) -> list:
    """Build the Phase objects for one catalog entry (old phaseworker). Loads the
    coded components, wires per-component `linked_with` and per-phase `based_on`
    within the entry, and applies the inherit flags. Returns [] if any phase in
    the entry is unmodeled. Atom types resolve against `atom_type_map` (the
    built-in library by default), shared across the entry so its phases reference
    one consistent set."""
    if not _entry_is_modeled(descr):
        return []
    if atom_type_map is None:
        atom_type_map = atom_type_library_map()

    phase_lookup: dict = {}
    component_lookup: dict = {}
    phases: list = []
    for phase_kwargs, code, comp_props in descr:
        kwargs = dict(phase_kwargs)
        reichweite = int(kwargs.pop("R", 0))
        name = kwargs.pop("name", "")
        based_on_name = kwargs.pop("based_on", None)
        inherit_probabilities = bool(kwargs.pop("inherit_probabilities", False))
        parts = [code[i:i + _CODE_LEN] for i in range(0, len(code), _CODE_LEN)]
        g = max(len(parts), 1)

        phase = Phase.create_empty(G=g, R=reichweite, name=name)
        phase.components = []
        for part in parts:
            for component in load_default_component(_ALIASES[part], atom_type_map):
                phase.components.append(component)
                for prop, value in comp_props.get(part, {}).items():
                    if prop == "linked_with":
                        target = component_lookup.get(value)
                        component.linked_with = target
                        component._linked_with_uuid = target.uuid if target else ""
                    else:
                        setattr(component, prop, value)
                component_lookup[part] = component
        phase.G = len(phase.components)

        if based_on_name and based_on_name in phase_lookup:
            phase.set_based_on(phase_lookup[based_on_name])
            # inherit the parent's stacking ratio (a no-op at G=1 - no free
            # probabilities). Must follow set_based_on, which links the models.
            if inherit_probabilities:
                phase.probabilities.inherit_all()
        for flag, value in kwargs.items():  # remaining kwargs are phase inherit_*
            if hasattr(phase, flag):
                setattr(phase, flag, value)

        phase_lookup[name] = phase
        phases.append(phase)
    return phases


def build_catalog_entry_by_name(display_name: str,
                                atom_type_map: dict | None = None) -> list:
    """Build the entry whose Add-Phase display name is `display_name`."""
    for name, descr in _CATALOG:
        if name == display_name:
            return build_catalog_entry(descr, atom_type_map)
    return []


def add_catalog_entry_to_project(project, display_name: str) -> list:
    """Build the named catalog entry and add its phases to `project`, merging
    their atom types in BY NAME: an atom type the project already has is reused
    (the built atoms re-point to it), one it lacks is adopted from the library.
    So a default phase computes immediately and never duplicates an existing
    atom type. Returns the added phases ([] if the entry is unknown/unmodeled)."""
    phases = build_catalog_entry_by_name(display_name)
    if not phases:
        return []
    by_name = {atom_type.name: atom_type for atom_type in project.atom_types}
    for phase in phases:
        for component in phase.components:
            for atom in list(component._layer_atoms) + list(component._interlayer_atoms):
                atom_type = atom.atom_type
                if atom_type is None:
                    continue
                existing = by_name.get(atom_type.name)
                if existing is None:
                    project.add_atom_type(atom_type)  # adopt the library type
                    by_name[atom_type.name] = atom_type
                elif existing is not atom_type:
                    atom.atom_type = existing  # dedup onto the project's own
        project.add_phase(phase)
    return phases


# ----------------------------------------------------------------------
# Default phases BY PHASE NAME (for the default-state composition comparison)
# ----------------------------------------------------------------------
#: {default phase name: catalog entry name}, built lazily and cached.
#: Building the whole catalog costs ~1.3 s, and the composition comparison needs
#: to look phases up repeatedly, so it is done once per session. The catalog is
#: read-only reference data shipped with the app, so the map cannot go stale.
_DEFAULT_PHASE_INDEX: dict | None = None


def default_phase_index() -> dict:
    """``{default phase name: catalog entry name}`` for every phase the catalog
    can build.

    A catalog ENTRY may build several phases - an expandable clay ships as a
    treatment triple (``...-AD`` / ``-EG`` / ``-350``) - so the phase name, not
    the entry name, is the identity a project phase is matched against. The
    names are unique across the whole catalog (224 of them at the time of
    writing), which is what makes a flat map safe."""
    global _DEFAULT_PHASE_INDEX
    if _DEFAULT_PHASE_INDEX is None:
        index: dict = {}
        for entry_name, _descr in _CATALOG:
            for phase in build_catalog_entry_by_name(entry_name):
                index[phase.name] = entry_name
        _DEFAULT_PHASE_INDEX = index
    return dict(_DEFAULT_PHASE_INDEX)


def default_phase_names() -> list:
    """Every default phase name, sorted - what the mapping dialog offers."""
    return sorted(default_phase_index())


def build_default_phase(phase_name: str, atom_type_map: dict | None = None):
    """Build ONE default phase by its name, or None if the catalog has no such
    phase. Returns a fresh object each call (the catalog is a recipe, not a
    cache), so the caller may treat it as its own."""
    entry_name = default_phase_index().get(phase_name)
    if entry_name is None:
        return None
    for phase in build_catalog_entry_by_name(entry_name, atom_type_map):
        if phase.name == phase_name:
            return phase
    return None
