# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QDockWidget, QFrame,
    QHeaderView, QMainWindow, QMenu, QMenuBar,
    QScrollArea, QSizePolicy, QStatusBar, QToolBar,
    QTreeView, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 800)
        self.actionNewProject = QAction(MainWindow)
        self.actionNewProject.setObjectName(u"actionNewProject")
        icon = QIcon(QIcon.fromTheme(u"document-new"))
        self.actionNewProject.setIcon(icon)
        self.actionOpenProject = QAction(MainWindow)
        self.actionOpenProject.setObjectName(u"actionOpenProject")
        icon1 = QIcon(QIcon.fromTheme(u"document-open"))
        self.actionOpenProject.setIcon(icon1)
        self.actionSaveProject = QAction(MainWindow)
        self.actionSaveProject.setObjectName(u"actionSaveProject")
        icon2 = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionSaveProject.setIcon(icon2)
        self.actionSaveProjectAs = QAction(MainWindow)
        self.actionSaveProjectAs.setObjectName(u"actionSaveProjectAs")
        icon3 = QIcon(QIcon.fromTheme(u"document-save-as"))
        self.actionSaveProjectAs.setIcon(icon3)
        self.actionEditProject = QAction(MainWindow)
        self.actionEditProject.setObjectName(u"actionEditProject")
        icon4 = QIcon(QIcon.fromTheme(u"document-properties"))
        self.actionEditProject.setIcon(icon4)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon5 = QIcon(QIcon.fromTheme(u"application-exit"))
        self.actionQuit.setIcon(icon5)
        self.actionRefreshGraph = QAction(MainWindow)
        self.actionRefreshGraph.setObjectName(u"actionRefreshGraph")
        icon6 = QIcon(QIcon.fromTheme(u"view-refresh"))
        self.actionRefreshGraph.setIcon(icon6)
        self.actionSaveGraph = QAction(MainWindow)
        self.actionSaveGraph.setObjectName(u"actionSaveGraph")
        self.actionRemoveBackground = QAction(MainWindow)
        self.actionRemoveBackground.setObjectName(u"actionRemoveBackground")
        self.actionSmoothData = QAction(MainWindow)
        self.actionSmoothData.setObjectName(u"actionSmoothData")
        self.actionShiftPattern = QAction(MainWindow)
        self.actionShiftPattern.setObjectName(u"actionShiftPattern")
        self.actionShowPlotToolbar = QAction(MainWindow)
        self.actionShowPlotToolbar.setObjectName(u"actionShowPlotToolbar")
        self.actionShowPlotToolbar.setCheckable(True)
        self.actionShowPlotToolbar.setChecked(False)
        self.actionAddSpecimen = QAction(MainWindow)
        self.actionAddSpecimen.setObjectName(u"actionAddSpecimen")
        icon7 = QIcon(QIcon.fromTheme(u"list-add"))
        self.actionAddSpecimen.setIcon(icon7)
        self.actionImportSpecimens = QAction(MainWindow)
        self.actionImportSpecimens.setObjectName(u"actionImportSpecimens")
        self.actionConvertToFixed = QAction(MainWindow)
        self.actionConvertToFixed.setObjectName(u"actionConvertToFixed")
        self.actionConvertToADS = QAction(MainWindow)
        self.actionConvertToADS.setObjectName(u"actionConvertToADS")
        self.actionEditPhases = QAction(MainWindow)
        self.actionEditPhases.setObjectName(u"actionEditPhases")
        self.actionEditComposition = QAction(MainWindow)
        self.actionEditComposition.setObjectName(u"actionEditComposition")
        self.actionRemoveComposition = QAction(MainWindow)
        self.actionRemoveComposition.setObjectName(u"actionRemoveComposition")
        self.actionExportOldMud = QAction(MainWindow)
        self.actionExportOldMud.setObjectName(u"actionExportOldMud")
        self.actionExportPyxrd = QAction(MainWindow)
        self.actionExportPyxrd.setObjectName(u"actionExportPyxrd")
        self.actionEditAtomTypes = QAction(MainWindow)
        self.actionEditAtomTypes.setObjectName(u"actionEditAtomTypes")
        self.actionEditMixtures = QAction(MainWindow)
        self.actionEditMixtures.setObjectName(u"actionEditMixtures")
        self.actionManual = QAction(MainWindow)
        self.actionManual.setObjectName(u"actionManual")
        icon8 = QIcon(QIcon.fromTheme(u"help-faq"))
        self.actionManual.setIcon(icon8)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon9 = QIcon(QIcon.fromTheme(u"help-about"))
        self.actionAbout.setIcon(icon9)
        self.actionTrimData = QAction(MainWindow)
        self.actionTrimData.setObjectName(u"actionTrimData")
        self.actionAddNoise = QAction(MainWindow)
        self.actionAddNoise.setObjectName(u"actionAddNoise")
        self.actionStripPeak = QAction(MainWindow)
        self.actionStripPeak.setObjectName(u"actionStripPeak")
        self.actionPeakProperties = QAction(MainWindow)
        self.actionPeakProperties.setObjectName(u"actionPeakProperties")
        self.actionEditBehaviours = QAction(MainWindow)
        self.actionEditBehaviours.setObjectName(u"actionEditBehaviours")
        self.actionEditBehaviours.setVisible(False)
        self.actionEditMarkers = QAction(MainWindow)
        self.actionEditMarkers.setObjectName(u"actionEditMarkers")
        self.actionSamplePoint = QAction(MainWindow)
        self.actionSamplePoint.setObjectName(u"actionSamplePoint")
        self.actionCrosshair = QAction(MainWindow)
        self.actionCrosshair.setObjectName(u"actionCrosshair")
        self.actionCrosshair.setCheckable(True)
        self.actionShowPhases = QAction(MainWindow)
        self.actionShowPhases.setObjectName(u"actionShowPhases")
        self.actionShowPhases.setCheckable(True)
        self.actionZoomIn = QAction(MainWindow)
        self.actionZoomIn.setObjectName(u"actionZoomIn")
        icon10 = QIcon(QIcon.fromTheme(u"zoom-in"))
        self.actionZoomIn.setIcon(icon10)
        self.actionZoomOut = QAction(MainWindow)
        self.actionZoomOut.setObjectName(u"actionZoomOut")
        icon11 = QIcon(QIcon.fromTheme(u"zoom-out"))
        self.actionZoomOut.setIcon(icon11)
        self.actionZoomReset = QAction(MainWindow)
        self.actionZoomReset.setObjectName(u"actionZoomReset")
        icon12 = QIcon(QIcon.fromTheme(u"zoom-fit-best"))
        self.actionZoomReset.setIcon(icon12)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.centralLayout = QVBoxLayout(self.centralWidget)
        self.centralLayout.setObjectName(u"centralLayout")
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.plotScrollArea = QScrollArea(self.centralWidget)
        self.plotScrollArea.setObjectName(u"plotScrollArea")
        self.plotScrollArea.setFrameShape(QFrame.NoFrame)
        self.plotScrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.plotScrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.plotScrollArea.setWidgetResizable(True)
        self.plotStackContainer = QWidget()
        self.plotStackContainer.setObjectName(u"plotStackContainer")
        self.plotStackLayout = QVBoxLayout(self.plotStackContainer)
        self.plotStackLayout.setSpacing(8)
        self.plotStackLayout.setObjectName(u"plotStackLayout")
        self.plotStackLayout.setContentsMargins(0, 0, 0, 0)
        self.plotScrollArea.setWidget(self.plotStackContainer)

        self.centralLayout.addWidget(self.plotScrollArea)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1280, 22))
        self.menuProject = QMenu(self.menuBar)
        self.menuProject.setObjectName(u"menuProject")
        self.menuExport = QMenu(self.menuBar)
        self.menuExport.setObjectName(u"menuExport")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuToolbars = QMenu(self.menuView)
        self.menuToolbars.setObjectName(u"menuToolbars")
        self.menuData = QMenu(self.menuBar)
        self.menuData.setObjectName(u"menuData")
        self.menuComposition = QMenu(self.menuBar)
        self.menuComposition.setObjectName(u"menuComposition")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionsToolbar = QToolBar(MainWindow)
        self.actionsToolbar.setObjectName(u"actionsToolbar")
        self.actionsToolbar.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.actionsToolbar)
        self.specimensDock = QDockWidget(MainWindow)
        self.specimensDock.setObjectName(u"specimensDock")
        self.specimensDockContents = QWidget()
        self.specimensDockContents.setObjectName(u"specimensDockContents")
        self.specimensDockContents.setMinimumSize(QSize(200, 0))
        self.specimensLayout = QVBoxLayout(self.specimensDockContents)
        self.specimensLayout.setObjectName(u"specimensLayout")
        self.specimensLayout.setContentsMargins(0, 0, 0, 0)
        self.specimensTree = QTreeView(self.specimensDockContents)
        self.specimensTree.setObjectName(u"specimensTree")
        self.specimensTree.setRootIsDecorated(False)
        self.specimensTree.setAlternatingRowColors(True)
        self.specimensTree.setUniformRowHeights(True)
        self.specimensTree.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.specimensTree.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.specimensTree.setAllColumnsShowFocus(True)

        self.specimensLayout.addWidget(self.specimensTree)

        self.specimensDock.setWidget(self.specimensDockContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.specimensDock)

        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuData.menuAction())
        self.menuBar.addAction(self.menuComposition.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuProject.addAction(self.actionNewProject)
        self.menuProject.addAction(self.actionOpenProject)
        self.menuProject.addAction(self.actionSaveProject)
        self.menuProject.addAction(self.actionSaveProjectAs)
        self.menuProject.addAction(self.menuExport.menuAction())
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionEditProject)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionQuit)
        self.menuExport.addAction(self.actionExportOldMud)
        self.menuExport.addAction(self.actionExportPyxrd)
        self.menuView.addAction(self.actionRefreshGraph)
        self.menuView.addAction(self.actionSaveGraph)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShowPhases)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionZoomReset)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRemoveBackground)
        self.menuView.addAction(self.actionSmoothData)
        self.menuView.addAction(self.actionShiftPattern)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuToolbars.addAction(self.actionShowPlotToolbar)
        self.menuData.addAction(self.actionAddSpecimen)
        self.menuData.addAction(self.actionImportSpecimens)
        self.menuData.addAction(self.actionConvertToFixed)
        self.menuData.addAction(self.actionConvertToADS)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionEditPhases)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionEditAtomTypes)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionEditMixtures)
        self.menuData.addSeparator()
        self.menuComposition.addAction(self.actionEditComposition)
        self.menuComposition.addAction(self.actionRemoveComposition)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout)
        self.actionsToolbar.addAction(self.actionNewProject)
        self.actionsToolbar.addAction(self.actionOpenProject)
        self.actionsToolbar.addAction(self.actionSaveProject)
        self.actionsToolbar.addSeparator()
        self.actionsToolbar.addAction(self.actionSaveGraph)
        self.actionsToolbar.addAction(self.actionTrimData)
        self.actionsToolbar.addSeparator()
        self.actionsToolbar.addAction(self.actionRemoveBackground)
        self.actionsToolbar.addAction(self.actionSmoothData)
        self.actionsToolbar.addAction(self.actionAddNoise)
        self.actionsToolbar.addAction(self.actionShiftPattern)
        self.actionsToolbar.addAction(self.actionStripPeak)
        self.actionsToolbar.addAction(self.actionPeakProperties)
        self.actionsToolbar.addSeparator()
        self.actionsToolbar.addAction(self.actionEditPhases)
        self.actionsToolbar.addAction(self.actionEditBehaviours)
        self.actionsToolbar.addAction(self.actionEditMixtures)
        self.actionsToolbar.addAction(self.actionEditAtomTypes)
        self.actionsToolbar.addSeparator()
        self.actionsToolbar.addAction(self.actionEditMarkers)
        self.actionsToolbar.addAction(self.actionSamplePoint)
        self.actionsToolbar.addAction(self.actionRefreshGraph)
        self.actionsToolbar.addSeparator()
        self.actionsToolbar.addAction(self.actionCrosshair)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MudLab", None))
        self.actionNewProject.setText(QCoreApplication.translate("MainWindow", u"&New Project", None))
        self.actionNewProject.setIconText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNewProject.setToolTip(QCoreApplication.translate("MainWindow", u"New Project", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNewProject.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenProject.setText(QCoreApplication.translate("MainWindow", u"&Open Project", None))
        self.actionOpenProject.setIconText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(tooltip)
        self.actionOpenProject.setToolTip(QCoreApplication.translate("MainWindow", u"Open Project", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpenProject.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveProject.setText(QCoreApplication.translate("MainWindow", u"&Save Project", None))
        self.actionSaveProject.setIconText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSaveProject.setToolTip(QCoreApplication.translate("MainWindow", u"Save Project", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSaveProject.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveProjectAs.setText(QCoreApplication.translate("MainWindow", u"Save Project &As", None))
#if QT_CONFIG(tooltip)
        self.actionSaveProjectAs.setToolTip(QCoreApplication.translate("MainWindow", u"Save Project as", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSaveProjectAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionEditProject.setText(QCoreApplication.translate("MainWindow", u"&Edit Project", None))
#if QT_CONFIG(tooltip)
        self.actionEditProject.setToolTip(QCoreApplication.translate("MainWindow", u"Edit Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionRefreshGraph.setText(QCoreApplication.translate("MainWindow", u"&Refresh Graph", None))
        self.actionRefreshGraph.setIconText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(tooltip)
        self.actionRefreshGraph.setToolTip(QCoreApplication.translate("MainWindow", u"Refresh the graph", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRefreshGraph.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveGraph.setText(QCoreApplication.translate("MainWindow", u"Save &Graph", None))
        self.actionSaveGraph.setIconText(QCoreApplication.translate("MainWindow", u"Save Graph", None))
#if QT_CONFIG(tooltip)
        self.actionSaveGraph.setToolTip(QCoreApplication.translate("MainWindow", u"Save Graph", None))
#endif // QT_CONFIG(tooltip)
        self.actionRemoveBackground.setText(QCoreApplication.translate("MainWindow", u"Remove &Background", None))
        self.actionRemoveBackground.setIconText(QCoreApplication.translate("MainWindow", u"Background", None))
#if QT_CONFIG(tooltip)
        self.actionRemoveBackground.setToolTip(QCoreApplication.translate("MainWindow", u"Remove Background", None))
#endif // QT_CONFIG(tooltip)
        self.actionSmoothData.setText(QCoreApplication.translate("MainWindow", u"&Smooth Data", None))
        self.actionSmoothData.setIconText(QCoreApplication.translate("MainWindow", u"Smooth data", None))
#if QT_CONFIG(tooltip)
        self.actionSmoothData.setToolTip(QCoreApplication.translate("MainWindow", u"Smooth Data", None))
#endif // QT_CONFIG(tooltip)
        self.actionShiftPattern.setText(QCoreApplication.translate("MainWindow", u"Shift &Pattern", None))
        self.actionShiftPattern.setIconText(QCoreApplication.translate("MainWindow", u"Shift data", None))
#if QT_CONFIG(tooltip)
        self.actionShiftPattern.setToolTip(QCoreApplication.translate("MainWindow", u"Shift Pattern", None))
#endif // QT_CONFIG(tooltip)
        self.actionShowPlotToolbar.setText(QCoreApplication.translate("MainWindow", u"Show plot toolbar", None))
        self.actionAddSpecimen.setText(QCoreApplication.translate("MainWindow", u"&Add Specimen", None))
#if QT_CONFIG(tooltip)
        self.actionAddSpecimen.setToolTip(QCoreApplication.translate("MainWindow", u"Add Specimen", None))
#endif // QT_CONFIG(tooltip)
        self.actionImportSpecimens.setText(QCoreApplication.translate("MainWindow", u"&Import Specimens", None))
#if QT_CONFIG(tooltip)
        self.actionImportSpecimens.setToolTip(QCoreApplication.translate("MainWindow", u"Import specimens", None))
#endif // QT_CONFIG(tooltip)
        self.actionConvertToFixed.setText(QCoreApplication.translate("MainWindow", u"Convert to Fixed Slit", None))
        self.actionConvertToADS.setText(QCoreApplication.translate("MainWindow", u"Convert to ADS", None))
        self.actionEditPhases.setText(QCoreApplication.translate("MainWindow", u"Edit &Phases", None))
        self.actionEditPhases.setIconText(QCoreApplication.translate("MainWindow", u"Phases", None))
#if QT_CONFIG(tooltip)
        self.actionEditPhases.setToolTip(QCoreApplication.translate("MainWindow", u"Phases", None))
#endif // QT_CONFIG(tooltip)
        self.actionEditComposition.setText(QCoreApplication.translate("MainWindow", u"&Edit composition...", None))
#if QT_CONFIG(tooltip)
        self.actionEditComposition.setToolTip(QCoreApplication.translate("MainWindow", u"Enter or edit the measured (XRF) oxide analysis for this project.", None))
#endif // QT_CONFIG(tooltip)
        self.actionRemoveComposition.setText(QCoreApplication.translate("MainWindow", u"&Remove composition", None))
#if QT_CONFIG(tooltip)
        self.actionRemoveComposition.setToolTip(QCoreApplication.translate("MainWindow", u"Delete the measured composition from this project.", None))
#endif // QT_CONFIG(tooltip)
        self.actionExportOldMud.setText(QCoreApplication.translate("MainWindow", u"MudLab (&old app) project...", None))
#if QT_CONFIG(tooltip)
        self.actionExportOldMud.setToolTip(QCoreApplication.translate("MainWindow", u"Write a .mud the original GTK MudLab can open.", None))
#endif // QT_CONFIG(tooltip)
        self.actionExportPyxrd.setText(QCoreApplication.translate("MainWindow", u"&PyXRD project...", None))
#if QT_CONFIG(tooltip)
        self.actionExportPyxrd.setToolTip(QCoreApplication.translate("MainWindow", u"Write a .pyxrd project file (best-effort).", None))
#endif // QT_CONFIG(tooltip)
        self.actionEditAtomTypes.setText(QCoreApplication.translate("MainWindow", u"Edit Atom &Types", None))
        self.actionEditAtomTypes.setIconText(QCoreApplication.translate("MainWindow", u"Atoms", None))
#if QT_CONFIG(tooltip)
        self.actionEditAtomTypes.setToolTip(QCoreApplication.translate("MainWindow", u"Atom Types", None))
#endif // QT_CONFIG(tooltip)
        self.actionEditMixtures.setText(QCoreApplication.translate("MainWindow", u"Edit &Mixtures", None))
        self.actionEditMixtures.setIconText(QCoreApplication.translate("MainWindow", u"Mixtures", None))
#if QT_CONFIG(tooltip)
        self.actionEditMixtures.setToolTip(QCoreApplication.translate("MainWindow", u"Mixtures", None))
#endif // QT_CONFIG(tooltip)
        self.actionManual.setText(QCoreApplication.translate("MainWindow", u"&Manual", None))
#if QT_CONFIG(shortcut)
        self.actionManual.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"&About MudLab", None))
        self.actionTrimData.setText(QCoreApplication.translate("MainWindow", u"Trim", None))
#if QT_CONFIG(tooltip)
        self.actionTrimData.setToolTip(QCoreApplication.translate("MainWindow", u"Trim Data", None))
#endif // QT_CONFIG(tooltip)
        self.actionAddNoise.setText(QCoreApplication.translate("MainWindow", u"Add noise", None))
#if QT_CONFIG(tooltip)
        self.actionAddNoise.setToolTip(QCoreApplication.translate("MainWindow", u"Add noise to experimental data", None))
#endif // QT_CONFIG(tooltip)
        self.actionStripPeak.setText(QCoreApplication.translate("MainWindow", u"Strip peaks", None))
#if QT_CONFIG(tooltip)
        self.actionStripPeak.setToolTip(QCoreApplication.translate("MainWindow", u"Strip Peak", None))
#endif // QT_CONFIG(tooltip)
        self.actionPeakProperties.setText(QCoreApplication.translate("MainWindow", u"Peak area", None))
#if QT_CONFIG(tooltip)
        self.actionPeakProperties.setToolTip(QCoreApplication.translate("MainWindow", u"Peak Properties", None))
#endif // QT_CONFIG(tooltip)
        self.actionEditBehaviours.setText(QCoreApplication.translate("MainWindow", u"Behaviours", None))
#if QT_CONFIG(tooltip)
        self.actionEditBehaviours.setToolTip(QCoreApplication.translate("MainWindow", u"Behaviours", None))
#endif // QT_CONFIG(tooltip)
        self.actionEditMarkers.setText(QCoreApplication.translate("MainWindow", u"Peaks", None))
#if QT_CONFIG(tooltip)
        self.actionEditMarkers.setToolTip(QCoreApplication.translate("MainWindow", u"List, add and label the peaks on this pattern", None))
#endif // QT_CONFIG(tooltip)
        self.actionSamplePoint.setText(QCoreApplication.translate("MainWindow", u"Select Point", None))
#if QT_CONFIG(tooltip)
        self.actionSamplePoint.setToolTip(QCoreApplication.translate("MainWindow", u"Identify Points", None))
#endif // QT_CONFIG(tooltip)
        self.actionCrosshair.setText(QCoreApplication.translate("MainWindow", u"Crosshair", None))
#if QT_CONFIG(tooltip)
        self.actionCrosshair.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle vertical crosshair cursor", None))
#endif // QT_CONFIG(tooltip)
        self.actionShowPhases.setText(QCoreApplication.translate("MainWindow", u"Show phase patterns", None))
#if QT_CONFIG(tooltip)
        self.actionShowPhases.setToolTip(QCoreApplication.translate("MainWindow", u"Overlay each phase's calculated contribution in its own colour", None))
#endif // QT_CONFIG(tooltip)
        self.actionZoomIn.setText(QCoreApplication.translate("MainWindow", u"Zoom &In", None))
#if QT_CONFIG(tooltip)
        self.actionZoomIn.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom in on the 2-theta axis", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionZoomIn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl++", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomOut.setText(QCoreApplication.translate("MainWindow", u"Zoom &Out", None))
#if QT_CONFIG(tooltip)
        self.actionZoomOut.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom out on the 2-theta axis", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionZoomOut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomReset.setText(QCoreApplication.translate("MainWindow", u"&Reset Zoom", None))
#if QT_CONFIG(tooltip)
        self.actionZoomReset.setToolTip(QCoreApplication.translate("MainWindow", u"Reset the plots to the full data range", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionZoomReset.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+0", None))
#endif // QT_CONFIG(shortcut)
        self.menuProject.setTitle(QCoreApplication.translate("MainWindow", u"&Project", None))
        self.menuExport.setTitle(QCoreApplication.translate("MainWindow", u"&Export", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.menuToolbars.setTitle(QCoreApplication.translate("MainWindow", u"Toolbars", None))
        self.menuData.setTitle(QCoreApplication.translate("MainWindow", u"&Data", None))
        self.menuComposition.setTitle(QCoreApplication.translate("MainWindow", u"&Composition", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.actionsToolbar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Actions", None))
        self.specimensDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Specimens", None))
    # retranslateUi

