"""Add Phase dialog. Design: ui/add_phase.ui.

Ported from the GTK AddPhaseView (phases/glade/addphase.glade). Modal,
like the old view: choose between a new empty phase (G 1-6, R 0-4), a
default phase from the catalog, or a raw pattern phase.
"""

from __future__ import annotations

from PySide6.QtWidgets import QDialog, QWidget

from mudlab.ui.ui_add_phase import Ui_AddPhaseDialog

# Placeholder catalog until the default phases port (old: .phs files in
# the default phases directory, regenerated by btn_generate_phases).
_DEMO_DEFAULT_PHASES = (
    "Kaolinite (default)",
    "Illite (default)",
    "Smectite (default)",
    "Chlorite (default)",
)


class AddPhaseDialog(QDialog):
    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.ui = Ui_AddPhaseDialog()
        self.ui.setupUi(self)

        self.ui.cmb_default_phases.addItems(_DEMO_DEFAULT_PHASES)

        for radio in (
            self.ui.rdb_empty_phase,
            self.ui.rdb_default_phase,
            self.ui.rdb_raw_pattern,
        ):
            radio.toggled.connect(self._update_sensitivities)
        # R > 0 requires more than one component.
        self.ui.G.valueChanged.connect(self._update_R_enabled)
        self._update_sensitivities()
        self._update_R_enabled(self.ui.G.value())

        self.ui.buttonBox.accepted.connect(self.accept)
        self.ui.buttonBox.rejected.connect(self.reject)

    # ------------------------------------------------------------------
    # Result accessors (old: get_phase_type / get_G / get_R)
    # ------------------------------------------------------------------
    @property
    def phase_type(self) -> str:
        if self.ui.rdb_empty_phase.isChecked():
            return "empty"
        if self.ui.rdb_default_phase.isChecked():
            return "default"
        return "raw"

    @property
    def G(self) -> int:
        return self.ui.G.value()

    @property
    def R(self) -> int:
        return self.ui.R.value()

    @property
    def default_phase(self) -> str:
        return self.ui.cmb_default_phases.currentText()

    def _update_sensitivities(self) -> None:
        self.ui.cont_empty_phase.setEnabled(self.ui.rdb_empty_phase.isChecked())
        self.ui.cont_default_phase.setEnabled(self.ui.rdb_default_phase.isChecked())

    def _update_R_enabled(self, G: int) -> None:
        if G <= 1:
            self.ui.R.setValue(0)
        self.ui.R.setEnabled(G > 1)
